# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerrapAT002 < Formula
  desc "CLI utility for finding any change between Terraform schemas"
  homepage "https://github.com/sirrend/terrap-cli.git"
  version "0.0.2"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.2/terrap-cli_0.0.2_darwin_arm64.tar.gz"
      sha256 "83cadee196bec13fc97e00da87bb697a222188ea9de8077ea6bf3cc731c65393"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.2/terrap-cli_0.0.2_darwin_amd64.tar.gz"
      sha256 "45ba5264ea17fd574988460f2847b6c555cf370f40490483391c3b4a809579b8"

      def install
        bin.install "terrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.2/terrap-cli_0.0.2_linux_armv6.tar.gz"
      sha256 "e69ab5b18243b238c158f57eda5ec2da0777acbabf04bc039859bbbd91408232"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.2/terrap-cli_0.0.2_linux_arm64.tar.gz"
      sha256 "255f633b18ddae3fb7d6aa581a57cc1862a97fc448588ca240b739ee4b616814"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.2/terrap-cli_0.0.2_linux_amd64.tar.gz"
      sha256 "9d25a875b1b6a45a02692323272b33993e436023516849e072c326ca4fb33544"

      def install
        bin.install "terrap"
      end
    end
  end
end
