# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerrapAT004 < Formula
  desc "CLI utility for finding any change between Terraform schemas"
  homepage "https://github.com/sirrend/terrap-cli.git"
  version "0.0.4"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_darwin_arm64.tar.gz"
      sha256 "5d6595a18c2c2e93e27a38bca396549128843f89f71a9eea43aecc8dde7152ee"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_darwin_amd64.tar.gz"
      sha256 "2550d055a7168a359b19286343cd56a6c2442a511914825869169d06dce71aaf"

      def install
        bin.install "terrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_linux_armv6.tar.gz"
      sha256 "e19595f64b4e6a31e3dfffe71e5a75becb6133d0c9268fdcd2f00047ae9a20d5"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_linux_arm64.tar.gz"
      sha256 "5a51035b635b8b30456945e8bc5b11e4a12e4abaa6dccd56b5b7239ac93fac51"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "d97b9e37eddaaa0aa0f8a4b1d7ab8f04824063ddcf1e83470974709ad28b40f8"

      def install
        bin.install "terrap"
      end
    end
  end
end
