# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerrapAT004 < Formula
  desc "CLI utility for finding any change between Terraform schemas"
  homepage "https://github.com/sirrend/terrap-cli.git"
  version "0.0.4"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_darwin_arm64.tar.gz"
      sha256 "c2e9c708b3f103ade5102c21f8af56507158885a00c48ebb81779d05b122dabb"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_darwin_amd64.tar.gz"
      sha256 "6b3f0ae778d0a7fd44e020c08ce42f6d9f1fc08c115a08a5074d1b3ffa3e4d52"

      def install
        bin.install "terrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_linux_armv6.tar.gz"
      sha256 "a1e413cabc5b6babde013438699d90deb86408605ee6296c39d450b41e471a1b"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_linux_arm64.tar.gz"
      sha256 "e8bf0bb6026aacbe8a44b635cfdb0bfc8ea343ff9a1f4c64f7fe17c9f48b5360"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.4/terrap-cli_0.0.4_linux_amd64.tar.gz"
      sha256 "32a9ba5879df6a4ed8d7bf4aac4467ac0c8cf060a09b6bdb0f6d86311a76a6b2"

      def install
        bin.install "terrap"
      end
    end
  end
end
