# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerrapAT001 < Formula
  desc "CLI utility for finding any change between Terraform schemas"
  homepage "https://github.com/sirrend/terrap-cli.git"
  version "0.0.1"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.1/terrap-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "1c10175a3042ac7789d7f3e9ad8bbaed19348118c7d292ae825713a1d91df1cf"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.1/terrap-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "8928437dd983d5a86021f60a650bbf1a1dae3fbbe1670e422f468cc039930838"

      def install
        bin.install "terrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.1/terrap-cli_0.0.1_linux_armv6.tar.gz"
      sha256 "619764b745e77e7680abd39f02787269c370bd3cbc61692b506e3e3d1541ff97"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.1/terrap-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "141b692ddd75f06fa0f85cd7f949b01bb9fdeb2059e13512ee6c151673ac5477"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.1/terrap-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "ca796204137eb5c2c7f3d287072dc405bc638fe3731068641065899498959e6e"

      def install
        bin.install "terrap"
      end
    end
  end
end
