# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TerrapAT003 < Formula
  desc "CLI utility for finding any change between Terraform schemas"
  homepage "https://github.com/sirrend/terrap-cli.git"
  version "0.0.3"
  license "Apache2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.3/terrap-cli_0.0.3_darwin_arm64.tar.gz"
      sha256 "3bc97f1b30fd9ed119707e8b570904206f74689d3778dc1d9a7cb650358342f9"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.3/terrap-cli_0.0.3_darwin_amd64.tar.gz"
      sha256 "f79328a25ddd95d2d452225e1a32ac038990e4b8953066d533ac52b477daa778"

      def install
        bin.install "terrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.3/terrap-cli_0.0.3_linux_armv6.tar.gz"
      sha256 "96579f3ee32895ca826b7790aac9b1d26d476f3b60866b047f65bfbf9384b998"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.3/terrap-cli_0.0.3_linux_arm64.tar.gz"
      sha256 "7b812f117307b7d2820a9b70d4d6e00d31cc3187d1db95cdf282c5ca7af4cc08"

      def install
        bin.install "terrap"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sirrend/terrap-cli/releases/download/v0.0.3/terrap-cli_0.0.3_linux_amd64.tar.gz"
      sha256 "766f8aed9b4e6cf946cf1b6e320a3a5a57937d7e13dd6ea5d091553cdd11238e"

      def install
        bin.install "terrap"
      end
    end
  end
end
